// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinOS.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NinOS.Infrastructure.Migrations
{
    [DbContext(typeof(NinOSDbContext))]
    [Migration("20260925013011_AddPromoBannerToDeliveryNote")]
    partial class AddPromoBannerToDeliveryNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NinOS.Domain.commission", b =>
                {
                    b.Property<int>("id_commission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_commission");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_commission"));

                    b.Property<decimal>("amount_bs")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_bs");

                    b.Property<decimal>("amount_usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_usd");

                    b.Property<decimal>("commission_percentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission_percentage");

                    b.Property<decimal>("exchange_rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("exchange_rate");

                    b.Property<int>("id_delivery_note")
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_note");

                    b.Property<int>("id_seller")
                        .HasColumnType("integer")
                        .HasColumnName("id_seller");

                    b.Property<bool>("is_paid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<DateTime?>("payout_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payout_date");

                    b.Property<string>("reference_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.HasKey("id_commission");

                    b.HasIndex("id_delivery_note");

                    b.HasIndex("id_seller");

                    b.ToTable("commission", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.commission_payment", b =>
                {
                    b.Property<int>("id_commission_payment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_commission_payment");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_commission_payment"));

                    b.Property<decimal>("amount_bs")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_bs");

                    b.Property<decimal>("amount_usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_usd");

                    b.Property<string>("bank_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<decimal>("exchange_rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("exchange_rate");

                    b.Property<int>("id_commission")
                        .HasColumnType("integer")
                        .HasColumnName("id_commission");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("payment_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_type");

                    b.Property<string>("reference_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.HasKey("id_commission_payment");

                    b.HasIndex("id_commission");

                    b.ToTable("commission_payment", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.customer", b =>
                {
                    b.Property<int>("id_customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_customer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_customer"));

                    b.Property<string>("business_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_name");

                    b.Property<string>("contact_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_name");

                    b.Property<string>("customer_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_code");

                    b.Property<string>("delivery_address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_address");

                    b.Property<string>("fiscal_address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fiscal_address");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("rif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rif");

                    b.Property<string>("seller_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seller_name");

                    b.HasKey("id_customer");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.delivery_note", b =>
                {
                    b.Property<int>("id_delivery_note")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_note");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_delivery_note"));

                    b.Property<decimal>("adjusted_total_usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("adjusted_total_usd");

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("cxc_observations")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cxc_observations");

                    b.Property<decimal?>("discount_percentage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("discount_percentage");

                    b.Property<DateTime?>("dispatch_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_customer")
                        .HasColumnType("integer")
                        .HasColumnName("id_customer");

                    b.Property<int?>("id_relacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_relacion");

                    b.Property<int>("id_seller")
                        .HasColumnType("integer")
                        .HasColumnName("id_seller");

                    b.Property<string>("note_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("note_number");

                    b.Property<int?>("note_type_id")
                        .HasColumnType("integer")
                        .HasColumnName("note_type_id");

                    b.Property<decimal?>("original_discount_percentage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("original_discount_percentage");

                    b.Property<decimal?>("original_volume_discount_percentage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("original_volume_discount_percentage");

                    b.Property<string>("promo_banner")
                        .HasColumnType("text");

                    b.Property<decimal?>("promo_discount_percentage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("promo_discount_percentage");

                    b.Property<string>("sales_observations")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sales_observations");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("total_amount_usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount_usd");

                    b.Property<decimal?>("volume_discount_percentage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("volume_discount_percentage");

                    b.HasKey("id_delivery_note");

                    b.HasIndex("id_customer");

                    b.HasIndex("id_relacion");

                    b.HasIndex("id_seller");

                    b.HasIndex("note_number")
                        .IsUnique();

                    b.HasIndex("note_type_id");

                    b.ToTable("delivery_note", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.note_detail", b =>
                {
                    b.Property<int>("id_note_detail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_note_detail");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_note_detail"));

                    b.Property<int>("id_delivery_note")
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_note");

                    b.Property<int?>("id_product")
                        .HasColumnType("integer")
                        .HasColumnName("id_product");

                    b.Property<int?>("id_promotion")
                        .HasColumnType("integer")
                        .HasColumnName("id_promotion");

                    b.Property<int>("quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("subtotal_usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal_usd");

                    b.Property<decimal>("unit_price_usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price_usd");

                    b.HasKey("id_note_detail");

                    b.HasIndex("id_delivery_note");

                    b.HasIndex("id_product");

                    b.HasIndex("id_promotion");

                    b.ToTable("note_detail", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.note_type", b =>
                {
                    b.Property<int>("id_note_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_note_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_note_type"));

                    b.Property<string>("calculation_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("calculation_type");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("conditions_template")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions_template");

                    b.Property<decimal>("default_discount_percentage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("default_discount_percentage");

                    b.Property<string>("discount_conditions_template")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discount_conditions_template");

                    b.Property<bool>("discount_configurable")
                        .HasColumnType("boolean")
                        .HasColumnName("discount_configurable");

                    b.Property<string>("header_title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("header_title");

                    b.Property<int?>("id_seller")
                        .HasColumnType("integer")
                        .HasColumnName("id_seller");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("mandatory_discount_percentage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("mandatory_discount_percentage");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal?>("promo_discount_percentage")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("promo_discount_percentage");

                    b.Property<int>("sort_order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("id_note_type");

                    b.HasIndex("id_seller");

                    b.ToTable("note_type", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.payment", b =>
                {
                    b.Property<int>("id_payment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_payment");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_payment"));

                    b.Property<decimal>("amount_bs")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_bs");

                    b.Property<decimal>("amount_usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_usd");

                    b.Property<string>("bank_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("exchange_rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("exchange_rate");

                    b.Property<int?>("id_delivery_note")
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_note");

                    b.Property<int?>("id_relacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_relacion");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("payment_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_type");

                    b.Property<string>("reference_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("id_payment");

                    b.HasIndex("id_delivery_note");

                    b.HasIndex("id_relacion");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.product", b =>
                {
                    b.Property<int>("id_product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_product");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_product"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("product_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_code");

                    b.Property<int>("stock_quantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<decimal>("unit_price_usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price_usd");

                    b.HasKey("id_product");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.promotion", b =>
                {
                    b.Property<int>("id_promotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_promotion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_promotion"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("promotion_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("promotion_code");

                    b.Property<decimal>("unit_price_usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price_usd");

                    b.HasKey("id_promotion");

                    b.ToTable("promotion", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.promotion_item", b =>
                {
                    b.Property<int>("id_promotion_item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_promotion_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_promotion_item"));

                    b.Property<int>("id_product")
                        .HasColumnType("integer")
                        .HasColumnName("id_product");

                    b.Property<int>("id_promotion")
                        .HasColumnType("integer")
                        .HasColumnName("id_promotion");

                    b.Property<int>("quantity_required")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_required");

                    b.HasKey("id_promotion_item");

                    b.HasIndex("id_product");

                    b.HasIndex("id_promotion");

                    b.ToTable("promotion_item", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.relacion", b =>
                {
                    b.Property<int>("id_relacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_relacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_relacion"));

                    b.Property<int>("relation_number")
                        .HasColumnType("integer")
                        .HasColumnName("relation_number");

                    b.Property<DateTime>("week_end")
                        .HasColumnType("date")
                        .HasColumnName("week_end");

                    b.Property<DateTime>("week_start")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("id_relacion");

                    b.HasIndex("relation_number")
                        .IsUnique();

                    b.HasIndex("week_start")
                        .IsUnique();

                    b.ToTable("relacion", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.seller", b =>
                {
                    b.Property<int>("id_seller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_seller");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_seller"));

                    b.Property<string>("customer_code_prefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_code_prefix");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("seller_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seller_code");

                    b.HasKey("id_seller");

                    b.ToTable("seller", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.commission", b =>
                {
                    b.HasOne("NinOS.Domain.delivery_note", null)
                        .WithMany()
                        .HasForeignKey("id_delivery_note")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinOS.Domain.seller", null)
                        .WithMany()
                        .HasForeignKey("id_seller")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NinOS.Domain.commission_payment", b =>
                {
                    b.HasOne("NinOS.Domain.commission", null)
                        .WithMany()
                        .HasForeignKey("id_commission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NinOS.Domain.delivery_note", b =>
                {
                    b.HasOne("NinOS.Domain.customer", null)
                        .WithMany()
                        .HasForeignKey("id_customer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NinOS.Domain.relacion", null)
                        .WithMany()
                        .HasForeignKey("id_relacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NinOS.Domain.seller", null)
                        .WithMany()
                        .HasForeignKey("id_seller")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NinOS.Domain.note_type", null)
                        .WithMany()
                        .HasForeignKey("note_type_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NinOS.Domain.note_detail", b =>
                {
                    b.HasOne("NinOS.Domain.delivery_note", null)
                        .WithMany()
                        .HasForeignKey("id_delivery_note")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinOS.Domain.product", null)
                        .WithMany()
                        .HasForeignKey("id_product")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NinOS.Domain.promotion", null)
                        .WithMany()
                        .HasForeignKey("id_promotion")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NinOS.Domain.note_type", b =>
                {
                    b.HasOne("NinOS.Domain.seller", null)
                        .WithMany()
                        .HasForeignKey("id_seller")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NinOS.Domain.payment", b =>
                {
                    b.HasOne("NinOS.Domain.delivery_note", null)
                        .WithMany()
                        .HasForeignKey("id_delivery_note")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NinOS.Domain.relacion", null)
                        .WithMany()
                        .HasForeignKey("id_relacion")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NinOS.Domain.promotion_item", b =>
                {
                    b.HasOne("NinOS.Domain.product", "product")
                        .WithMany()
                        .HasForeignKey("id_product")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NinOS.Domain.promotion", "promotion")
                        .WithMany("items")
                        .HasForeignKey("id_promotion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("promotion");
                });

            modelBuilder.Entity("NinOS.Domain.promotion", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
