// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinOS.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NinOS.Infrastructure.Migrations
{
    [DbContext(typeof(NinOSDbContext))]
    [Migration("20260722224028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NinOS.Domain.commission", b =>
                {
                    b.Property<int>("id_commission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_commission");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_commission"));

                    b.Property<decimal>("amount_usd")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_usd");

                    b.Property<decimal>("commission_percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_percentage");

                    b.Property<int>("id_delivery_note")
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_note");

                    b.Property<int>("id_seller")
                        .HasColumnType("integer")
                        .HasColumnName("id_seller");

                    b.Property<bool>("is_paid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<DateTime?>("payout_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payout_date");

                    b.HasKey("id_commission");

                    b.HasIndex("id_delivery_note");

                    b.HasIndex("id_seller");

                    b.ToTable("commission", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.customer", b =>
                {
                    b.Property<int>("id_customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_customer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_customer"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<string>("customer_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_code");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("id_customer");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.delivery_note", b =>
                {
                    b.Property<int>("id_delivery_note")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_note");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_delivery_note"));

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int>("id_customer")
                        .HasColumnType("integer")
                        .HasColumnName("id_customer");

                    b.Property<int>("id_seller")
                        .HasColumnType("integer")
                        .HasColumnName("id_seller");

                    b.Property<string>("note_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("note_number");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("total_amount_usd")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount_usd");

                    b.HasKey("id_delivery_note");

                    b.HasIndex("id_customer");

                    b.HasIndex("id_seller");

                    b.ToTable("delivery_note", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.note_detail", b =>
                {
                    b.Property<int>("id_note_detail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_note_detail");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_note_detail"));

                    b.Property<int>("id_delivery_note")
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_note");

                    b.Property<int>("id_product")
                        .HasColumnType("integer")
                        .HasColumnName("id_product");

                    b.Property<int>("quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("subtotal_usd")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal_usd");

                    b.Property<decimal>("unit_price_usd")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price_usd");

                    b.HasKey("id_note_detail");

                    b.HasIndex("id_delivery_note");

                    b.HasIndex("id_product");

                    b.ToTable("note_detail", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.payment", b =>
                {
                    b.Property<int>("id_payment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_payment");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_payment"));

                    b.Property<decimal>("amount_bs")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_bs");

                    b.Property<decimal>("amount_usd")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_usd");

                    b.Property<decimal>("exchange_rate")
                        .HasColumnType("numeric")
                        .HasColumnName("exchange_rate");

                    b.Property<int>("id_delivery_note")
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_note");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.HasKey("id_payment");

                    b.HasIndex("id_delivery_note");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.product", b =>
                {
                    b.Property<int>("id_product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_product");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_product"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("product_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_code");

                    b.Property<int>("stock_quantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<decimal>("unit_price_usd")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price_usd");

                    b.HasKey("id_product");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.seller", b =>
                {
                    b.Property<int>("id_seller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_seller");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_seller"));

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("seller_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seller_code");

                    b.HasKey("id_seller");

                    b.ToTable("seller", (string)null);
                });

            modelBuilder.Entity("NinOS.Domain.commission", b =>
                {
                    b.HasOne("NinOS.Domain.delivery_note", null)
                        .WithMany()
                        .HasForeignKey("id_delivery_note")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinOS.Domain.seller", null)
                        .WithMany()
                        .HasForeignKey("id_seller")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NinOS.Domain.delivery_note", b =>
                {
                    b.HasOne("NinOS.Domain.customer", null)
                        .WithMany()
                        .HasForeignKey("id_customer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NinOS.Domain.seller", null)
                        .WithMany()
                        .HasForeignKey("id_seller")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NinOS.Domain.note_detail", b =>
                {
                    b.HasOne("NinOS.Domain.delivery_note", null)
                        .WithMany()
                        .HasForeignKey("id_delivery_note")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinOS.Domain.product", null)
                        .WithMany()
                        .HasForeignKey("id_product")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NinOS.Domain.payment", b =>
                {
                    b.HasOne("NinOS.Domain.delivery_note", null)
                        .WithMany()
                        .HasForeignKey("id_delivery_note")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
